### ISSUE TITLE
react glob import error in shadow-cljs

### ISSUE THREAD

**Issue by alidcastano** [Lokeh/helix#1]
trying to use helix with shadow-cljs and getting following error 
> --- helix/impl/class.js:1
> Namespace imports (goog:some.Namespace) cannot use import * as. Did you mean to import React from 'goog:shadow.js.shim.module$react';?

**Comment by Lokeh** [comment]
That's really strange; when I run the `:dev` build in this repo, it wouldn't work unless I used the glob syntax. 😬

Here's the error I get when I try and run your code change from a REPL:

```
TypeError: Cannot read property 'Component' of undefined
    at Object.createComponent$$module$helix$impl$class [as createComponent] (/js/cljs-runtime/module$helix$impl$class.js:26:93)
    at helix$core$create_component (/js/cljs-runtime/helix.core.js:158:32)
 ```

AFAICT I think your code _should_ be correct, but I'm unsure why there would be this discrepancy between a React Native and a browser build. I'll bring it up to thheller and see if he has any insight.

**Comment by alidcastano** [comment]
yea, they're different built targets in shadow-cljs so they're likely being handled differently

specially since react native code isn't usually transpiled in packages, whereas browser code usually is... so maybe that's why glob syntax didn't work in former scenario but no clue why destructuring an import wouldn't work
