### ISSUE TITLE
Consider keyword version of the spread operator

### ISSUE THREAD

**Issue by darwin** [Lokeh/helix#19]
`&` is a special symbol acting as a spread operator in `$` macro expansion.

```clj
($ :div {:prop "val" & rest-props} ...)
```

This causes minor issue in Cursive which sees a normal map and complains about unresolved symbol `&`. I think adding support for `:&` to be optionally used in place of `&` should not hurt anynone.

```clj
($ :div {:prop "val" :& rest-props} ...)
```

See https://github.com/darwin/helix/commit/be5c3dc00790f60de5e22bdbc1ea9250b8b1981b

**Comment by Lokeh** [comment]
I'd like to have it one or another, rather than have people open up a codebase and figure out if they should use `&` or `:&` or be inconsistent (probably based on what editor the author uses).

**Comment by darwin** [comment]
Ok, don't worry. You may close this. I will probably keep a fork of helix with some custom patches on top, so it is not a big issue for me atm.

**Comment by Lokeh** [comment]
I'll keep this open as I think I want to move to a keyword version to not mess with Cursive users.

**Comment by khmelevskii** [comment]
Yes, it would be great to use `:&` instead of `&` because currently I have joker warning for this symbol
