### ISSUE TITLE
Advanced mode: dynamic arity dispatch of helix.core/create-element

### ISSUE THREAD

**Issue by darwin** [Lokeh/helix#20]
I just looked at advanced mode output and `$` macros tend to emit a lot of calls to `helix.core/create-element`.

Unfortunately currently this does not inline well in advanced mode. Dynamic arity dispatch code is generated everywhere.

I started some investigation, but didn't find proper solution to refer to react/createElement directly from a macro (might be shadow-cljs issue):
https://github.com/binaryage/cljs-react-three-fiber/commit/1d23a5050c540a19804182dfcb1545eb09356f92

**Comment by darwin** [comment]
Found a workaround: https://github.com/binaryage/cljs-react-three-fiber/commit/3838dd6f3871660e67aabf9280dc7a6e1d484bfc

**Comment by Lokeh** [comment]
Wow, nice!

**Comment by Lokeh** [comment]
A related thing I've thought about for awhile: emit the actual element object, instead of a call to createElement. Or use our own fn at least that wouldn't pessimistically copy all of the props, similar to https://github.com/reactjs/rfcs/pull/107

**Comment by Lokeh** [comment]
@darwin I would take a PR for this. I can also do it myself, if you're not interested

**Comment by darwin** [comment]
@Lokeh this is really a small change, it will be better if you did it exactly where you wanted it.

I think calling react/createElement is alwasys fine in dev mode. It contains some defensive dev-time checks and source locations.  

We can optimize release mode path to directly call `ReactElement`, but we must be careful to not break react's assumptions. This would lead to hard-to-debug-in-release-mode-only issues.

**Comment by Lokeh** [comment]
Closed with 02b1e20
