### ISSUE TITLE
Allow user-customization of display names

### ISSUE THREAD

**Issue by darwin** [Lokeh/helix#21]
Since this would be used only in dev mode. This should be done on client side for better flexibility.

Something along these lines:
https://github.com/darwin/helix/commit/e43f4b7d7354eb97b3d354c5f192623d287f2793
https://github.com/binaryage/cljs-react-three-fiber/commit/eb5b81d094400aa6142c59ffccf7ec8a3a92c7ca#diff-2f8098cbd9d667f556f10988d437ff8f

**Comment by Lokeh** [comment]
This can be covered by [creating a custom macro](https://github.com/Lokeh/helix/blob/master/docs/pro-tips.md#create-a-custom-macro)
