### ISSUE TITLE
fast-refresh with react-native

### ISSUE THREAD

**Issue by aiba** [Lokeh/helix#30]
I'm trying to get started with helix and react-native, and am especially interested in getting react fast refresh working.

I couldn't get fast-refresh to work with helix 0.0.8.  Perhaps someone could point me in the right direction toward getting fast refresh to work?

I tried to boil things down to a minimal example repo here: https://github.com/aiba/helix-react-native

**Comment by aiba** [comment]
Per #29 I got this working with the latest helix code.

I'd suggest putting a note in the documentation that helix works with react-native, and that you need to tell the react-native dev simulator to "Disable Fast Refresh" when you do your own helix fast-refresh hooking.

**Comment by Lokeh** [comment]
I haven’t used React Native since they introduced the Fast Refresh feature. Would you be willing to open a PR with instructions on how to get started with it? I bet others would appreciate it!

**Comment by aiba** [comment]
Yes, I'd be happy to.

Hooking into react's own fast-refresh feature is a huge selling point for anyone working with react-native.  Especially when using navigation libraries like [react-navigation](https://reactnavigation.org/), which [don't quite work](https://github.com/thheller/shadow-cljs/issues/349) with the other clojurescript ways of doing live code reloading.  With helix, however, I have confirmed react-navigation works perfectly.

I will open a PR with instructions and examples, based on what I've learned.

**Comment by Lokeh** [comment]
Great!

Please be aware, there's currently a couple WIP things about the React Refresh integration:
- Custom hooks are not invalidated correctly all the time; there are plans to leverage `defhook` to provide this functionality
- When testing with web, transitive namespaces do not trigger a refresh. Example:

```clojure
(ns app.a
  (:require
   [app.b]
   [helix.core :refer [defnc]])

(defnc app
  []
  (app.b/greet "Refresh"))
```

```clojure
(ns app.b
  (:require 
   [app.c]))

(defn greet
  [name]
  (str app.c/greeting ", " name "!"))
```

```clojure
(ns app.c)

(def greeting "Bonjour")
```

Editing `app.c/greeting` to `"Hello"` will not trigger `app.a/app` to refresh.

I'm not sure if this behavior is different in React Native; it is dependent on whether `app.a` gets reloaded when transitive namespaces are edited. shadow-cljs on the web currently only reloads namespaces that directly depend on the edited namespace.

**Comment by aiba** [comment]
>  shadow-cljs on the web currently only reloads namespaces that directly depend on the edited namespace.

Funny you should mention this.  For this exact scenario, shadow-cljs now has a `{:reload-strategy :full}` option.  See https://github.com/thheller/shadow-cljs/issues/349#issuecomment-590414443

**Comment by Lokeh** [comment]
Oh! That's actually fantastic; it had been on my mind to try and create PR for shadow for that and haven't had nearly the time to get spun up on it.

Noting that config option in the Fast Refresh docs would also be a good addition.
